### YamlMime:UniversalReference
items:
  - uid: office-ui-fabric-react.IStyleSheetConfig
    summary: Stylesheet config.
    name: IStyleSheetConfig
    fullName: IStyleSheetConfig
    langs:
      - typeScript
    type: interface
    package: office-ui-fabric-react
    children:
      - office-ui-fabric-react.IStyleSheetConfig.defaultPrefix
      - office-ui-fabric-react.IStyleSheetConfig.injectionMode
      - office-ui-fabric-react.IStyleSheetConfig.namespace
      - office-ui-fabric-react.IStyleSheetConfig.onInsertRule
  - uid: office-ui-fabric-react.IStyleSheetConfig.defaultPrefix
    summary: Default 'displayName' to use for a className.
    name: defaultPrefix
    fullName: defaultPrefix
    langs:
      - typeScript
    type: property
    syntax:
      content: 'defaultPrefix?: string;'
      return:
        type:
          - string
  - uid: office-ui-fabric-react.IStyleSheetConfig.injectionMode
    summary: Injection mode for how rules are inserted.
    name: injectionMode
    fullName: injectionMode
    langs:
      - typeScript
    type: property
    syntax:
      content: 'injectionMode?: InjectionMode;'
      return:
        type:
          - InjectionMode
  - uid: office-ui-fabric-react.IStyleSheetConfig.namespace
    summary: Default 'namespace' to attach before the className.
    name: namespace
    fullName: namespace
    langs:
      - typeScript
    type: property
    syntax:
      content: 'namespace?: string;'
      return:
        type:
          - string
  - uid: office-ui-fabric-react.IStyleSheetConfig.onInsertRule
    summary: Callback executed when a rule is inserted.
    name: onInsertRule
    fullName: onInsertRule
    langs:
      - typeScript
    type: property
    syntax:
      content: 'onInsertRule?: (rule: string) => void;'
      return:
        type:
          - '(rule: string) => void'
