pool:
  name: Hosted Ubuntu 1604
  demands: npm

steps:
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: '10.x'
    checkLatest: true

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    verbose: false
    customCommand: run build

- script: >
    node
    lib/start.js
    $(Build.ArtifactStagingDirectory)/doc-files/docs
  displayName: Generate examples and API Documenter Config

  - script: >
    node
    lib/get-fabric-version.js
    $(Build.ArtifactStagingDirectory)/FABRIC_VERSION
  displayName: Get OUFR Version

- script: >
    node
    node_modules/.bin/api-documenter
    generate
    --output-folder $(Build.ArtifactStagingDirectory)/doc-files/api
  displayName: Run API Documenter

- task: CopyFiles@2
  displayName: 'Copy static doc data'
  inputs:
    SourceFolder: 'static-doc-data'
    TargetFolder: $(Build.ArtifactStagingDirectory)/doc-files/

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: DOC-FILES'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/doc-files'
    ArtifactName: DOC-FILES

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: FABRIC-VERSION'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/FABRIC_VERSION'
    ArtifactName: FABRIC_VERSION
